cheques_index:
    path:     /
    defaults: { _controller: "ProjectSitepDfinBundle:Cheques:index" }
    methods:  GET

cheques_show:
    path:     /{id}/show
    defaults: { _controller: "ProjectSitepDfinBundle:Cheques:show" }
    methods:  GET

cheques_new:
    path:     /new
    defaults: { _controller: "ProjectSitepDfinBundle:Cheques:new" }
    methods:  [GET, POST]

cheques_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProjectSitepDfinBundle:Cheques:edit" }
    methods:  [GET, POST]

cheques_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProjectSitepDfinBundle:Cheques:delete" }
    methods:  DELETE
