bs_index:
    path:     /
    defaults: { _controller: "ProjectSitepDasfaBundle:BulletinSoin:index" }
    methods:  GET

bs_show:
    path:     /{id}/show
    defaults: { _controller: "ProjectSitepDasfaBundle:BulletinSoin:show" }
    methods:  GET

bs_new:
    path:     /new
    defaults: { _controller: "ProjectSitepDasfaBundle:BulletinSoin:new" }
    methods:  [GET, POST]

bs_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProjectSitepDasfaBundle:BulletinSoin:edit" }
    methods:  [GET, POST]

bs_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProjectSitepDasfaBundle:BulletinSoin:delete" }
    methods:  DELETE
